[profile.release]
opt-level = 3
lto = true
codegen-units = 16
panic = 'abort'
strip = 'symbols'
debug = false
debug-assertions = false
overflow-checks = false
rpath = false

[package]
name = "transgender"
version = "1.5.6"
edition = "2021"

[dependencies]
libc = "0.2"
regex-lite = "0.1.6"
