# i686 can use the default gcc
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc-14"
ar = "aarch64-linux-gnu-ar-14"

[target.loongarch64-unknown-linux-gnu]
linker = "loongarch64-linux-gnu-gcc-14"
ar = "loongarch64-linux-gnu-ar-14"

[target.riscv64gc-unknown-linux-gnu]
linker = "riscv64-linux-gnu-gcc-14"
ar = "riscv64-linux-gnu-ar-14"
